markdown:       rdiscount
highlighter:    pygments
permalink:      ./:title
name:           Perfection Kills
description:    "Javascript rants and findings, by kangax"
author:         kangax
twitter_username: kangax
url:            https://perfectionkills.com
encoding:       UTF-8
exclude:        ["README", "vendor"]
sass:
  style:        compressed
plugins:
  - jekyll-feed
  - jekyll-gist
