markdown:       rdiscount
pygments:       true
permalink:      ./:title
name:           Perfection Kills
description:    "Javascript rants and findings, by kangax"
url:            http://perfectionkills.com
encoding:       UTF-8

exclude:        ["README"]

compress_html:
  clippings: [html, head, title, base, link, meta, style, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header, footer, address, p, hr, blockquote, ol, ul, li, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th]
  endings: [html, head, body, li, dt, dd, p, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
